name: 'DargStack: rgen'

permissions: {}

on:
  workflow_call:
    inputs:
      APT_PACKAGES:
        type: string
      NODE_VERSION:
        type: string
      NODE_VERSION_FILE:
        default: .nvmrc
        type: string
      PACKAGE_MANAGER:
        default: pnpm
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
        if: inputs.APT_PACKAGES != ''
        with:
          packages: ${{ inputs.APT_PACKAGES }}
          version: 1.0

      - name: Setup package manager
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: ${{ inputs.PACKAGE_MANAGER }}
          node-version: ${{ inputs.NODE_VERSION }}
          node-version-file: ${{ inputs.NODE_VERSION_FILE }}

      - name: Install dependencies
        run: ${{ inputs.PACKAGE_MANAGER }} install

      - name: dargstack rgen
        run: ${{ inputs.PACKAGE_MANAGER }} exec dargstack_rgen --validate

      - name: dargstack derive
        run: |
          mkdir ~/scripts/
          wget "https://raw.githubusercontent.com/dargstack/dargstack/master/src/dargstack" -O ~/scripts/dargstack
          chmod +x ~/scripts/dargstack
          ~/scripts/dargstack derive
