name: Docker

on:
  workflow_call:
    inputs:
      TARGET:
        default: production
        required: false
        type: string
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      DOCKER_HUB_USER_NAME:
        required: true

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - uses: dargmuesli/docker-build-cache-config-action@v1.9.0
        id: cache
        with:
          image: ${{ github.repository }}
          tag-prefix: ${{ inputs.TARGET }}_

      - name: Docker Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Registry login
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER_NAME }}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            CI=true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ steps.meta.outputs.tags != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ inputs.TARGET }}
