name: 'Lint: Workflow YAML'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: false

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'
