name: 'Lint: Workflow YAML'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml"]'
