name: 'Lint: Workflow YAML'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml"]'
