name: 'Lint: Workflow YAML'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml"]'
