name: 'Lint: Workflow YAML'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Lint yaml
        uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml"]'
