name: 'Lint: Workflow YAML'

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Lint yaml
        uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml"]'
