name: 'Release: Scheduled'

on:
  workflow_call:
    inputs:
      PACKAGE_JSON_PATH:
        default: package.json
        required: false
        type: string
      IS_DEBOUNCED:
        default: true
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 AM UTC on the default branch

jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      timestamp-diff: ${{ steps.diff.outputs.timestamp-diff }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1.0
      - name: Get seconds from previous tag to now
        id: diff
        shell: bash
        env:
          TIMESTAMP_TAG: ${{ steps.previoustag.outputs.timestamp }}
        run: |
          echo "$(expr $(printf '%(%s)T') - $TIMESTAMP_TAG)"
          echo "::set-output name=timestamp-diff::$(expr $(printf '%(%s)T') - $TIMESTAMP_TAG)"

  schedule-release:
    runs-on: ubuntu-latest
    needs: analyze-tags
    if: inputs.IS_DEBOUNCED == false || needs.analyze-tags.outputs.timestamp-diff > 604800 # 604800 equal one week.
    steps:
      - name: Debug
        shell: bash
        env:
          TIMESTAMP_DIFF: ${{ needs.analyze-tags.outputs.timestamp-diff }}
        run: |
          echo "$TIMESTAMP_DIFF"
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ needs.analyze-tags.outputs.previous-tag }}
      - name: manifest Version
        uses: deef0000dragon1/json-edit-action@cb3f7455e89d659879ab7e4a55cbc9b10c36a713 # renovate: tag=v1
        env:
          KEY: scheduleVersion
          VALUE: ${{ steps.semvers.outputs.patch }}
          FILE: ${{ inputs.PACKAGE_JSON_PATH || 'package.json' }}
      - uses: stefanzweifel/git-auto-commit-action@fd157da78fa13d9383e5580d1fd1184d89554b51 # tag=v4.15.1
        with:
          commit_message: 'fix(release): schedule release'
