name: 'Release: Assets'

on:
  workflow_call:
    inputs:
      TARGET:
        default: build
        required: false
        type: string

jobs:
  release-assets:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Docker Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1.7.0

      - name: Build "${{ inputs.TARGET }}"
        run: |
          docker buildx build \
            --build-arg CI=true \
            --cache-from=${{ github.repository }}:cache \
            -t stage_build \
            --target ${{ inputs.TARGET }} \
            --load \
            .
          docker container create --name extract stage_build
          docker container cp extract:/srv/app/ ./dist/
          docker container rm -f extract

      - name: Zip
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28 # renovate: tag=v1.0.0
        with:
          args: zip -qq -r ./${{ github.event.repository.name }}.zip ./dist/

      - name: GitHub Release Asset
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v1
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
