name: 'Release: Scheduled'

permissions: {}

on:
  schedule:
    - cron: '0 0 * * 3' # Every Wednesday at 00:00 AM UTC on the default branch
  workflow_call:
    inputs:
      EXTRA_PLUGINS:
        type: string
      GH_APP_ID:
        type: string
      IS_DEBOUNCED:
        default: ${{ github.event_name != 'workflow_dispatch' }}
        type: boolean
      NODE_VERSION:
        default: '22'
        type: string
      NODE_VERSION_FILE:
        type: string
      PACKAGE_MANAGER:
        default: npm
        type: string
      RELEASE_AS:
        default: patch
        type: string
    secrets:
      GH_APP_PRIVATE_KEY:
        required: false
      PERSONAL_ACCESS_TOKEN:
        required: false
  workflow_dispatch:
    inputs:
      EXTRA_PLUGINS:
        type: string
      IS_DEBOUNCED:
        default: true
        type: boolean
      NODE_VERSION:
        default: '22'
        type: string
      NODE_VERSION_FILE:
        type: string
      PACKAGE_MANAGER:
        default: npm
        type: string
      RELEASE_AS:
        default: patch
        type: string

jobs:
  analyze-tags:
    name: Analyze tags
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      timestamp-diff: ${{ steps.diff.outputs.timestamp-diff }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # fetch complete history to find the last git tag

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0

      - name: Get seconds from previous tag to now
        id: diff
        shell: bash
        env:
          TIMESTAMP_TAG: ${{ steps.previoustag.outputs.timestamp }}
        run: |
          echo "$(($(printf '%(%s)T') - TIMESTAMP_TAG))"
          echo "timestamp-diff=$(($(printf '%(%s)T') - TIMESTAMP_TAG))" >> "$GITHUB_OUTPUT"

      - name: Debug
        env:
          TIMESTAMP_DIFF: ${{ steps.diff.outputs.timestamp-diff }}
        run: |
          echo "$TIMESTAMP_DIFF"
          echo "-"
          echo "inputs.IS_DEBOUNCED: ${{ inputs.IS_DEBOUNCED }}"
          echo "inputs.IS_DEBOUNCED == '': ${{ inputs.IS_DEBOUNCED == '' }}"
          echo "inputs.IS_DEBOUNCED == null: ${{ inputs.IS_DEBOUNCED == null }}"
          echo "inputs.IS_DEBOUNCED > '': ${{ inputs.IS_DEBOUNCED > '' }}"
          echo "-"
          echo "inputs.IS_DEBOUNCED == false: ${{ inputs.IS_DEBOUNCED == false }}"
          echo "inputs.IS_DEBOUNCED == 'false': ${{ inputs.IS_DEBOUNCED == 'false' }}"
          echo "inputs.IS_DEBOUNCED == true: ${{ inputs.IS_DEBOUNCED == true }}"
          echo "inputs.IS_DEBOUNCED == 'true': ${{ inputs.IS_DEBOUNCED == 'true' }}"
          echo "-"
          echo "steps.diff.outputs.timestamp-diff > 604800: ${{ steps.diff.outputs.timestamp-diff > 604800 }}"
          echo "contains(inputs.IS_DEBOUNCED, 'false') || steps.diff.outputs.timestamp-diff > 604800: ${{ inputs.IS_DEBOUNCED == false || steps.diff.outputs.timestamp-diff > 604800 }}"

  schedule-release:
    needs: analyze-tags
    if: contains(inputs.IS_DEBOUNCED, 'false') || needs.analyze-tags.outputs.timestamp-diff > 604800 # 604800 equal one week.
    name: Schedule release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Create app token
        id: app-token
        if: inputs.GH_APP_ID != '' || vars.GH_APP_ID != ''
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ inputs.GH_APP_ID || vars.GH_APP_ID }}
          permission-contents: write
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token || secrets.PERSONAL_ACCESS_TOKEN || github.token }}

      - name: Setup package manager
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: ${{ inputs.PACKAGE_MANAGER }}
          node-version: ${{ inputs.NODE_VERSION }}
          node-version-file: ${{ inputs.NODE_VERSION_FILE }}

      - name: Release (forced)
        run: |
          PACKAGES=" \
            @semantic-release/changelog \
            @semantic-release/commit-analyzer \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits \
            $EXTRA_PLUGINS \
            semantic-release"
          if [ "$PACKAGE_MANAGER" = "pnpm" ]; then
            pnpm add --dev $PACKAGES
            pnpm exec semantic-release --release-as "$RELEASE_AS"
          elif [ "$PACKAGE_MANAGER" = "yarn" ]; then
            yarn add -D $PACKAGES
            yarn semantic-release --release-as "$RELEASE_AS"
          else
            npm install --save-dev $PACKAGES
            npx semantic-release --release-as "$RELEASE_AS"
          fi
        env:
          EXTRA_PLUGINS: ${{ inputs.EXTRA_PLUGINS }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN || steps.app-token.outputs.token || github.token }}
          PACKAGE_MANAGER: ${{ inputs.PACKAGE_MANAGER }}
          RELEASE_AS: ${{ inputs.RELEASE_AS }}
