name: 'Release: Assets'

on:
  workflow_call:
    inputs:
      TARGET:
        default: build
        required: false
        type: string

jobs:
  release-assets:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Docker Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0

      - name: Build "${{ inputs.TARGET }}"
        run: |
          docker buildx build \
            --cache-from=${{ github.repository }}:cache \
            -t stage_build \
            --target ${{ inputs.TARGET }} \
            --load \
            .
          docker container create --name extract stage_build
          docker container cp extract:/srv/app/ ./dist/
          docker container rm -f extract

      - name: Zip
        uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28 # renovate: tag=v1.0.0
        with:
          args: zip -qq -r ./${{ github.event.repository.name }}.zip ./dist/

      - name: GitHub Release Asset
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v1
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
