name: 'Release: Scheduled'

on:
  schedule:
    - cron: '0 0 * * 3' # Every Wednesday at 00:00 AM UTC on the default branch
  workflow_call:
    inputs:
      IS_DEBOUNCED:
        default: ${{ github.event_name != 'workflow_dispatch' }}
        required: false
        type: boolean
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      IS_DEBOUNCED:
        default: true
        required: false
        type: boolean

jobs:
  analyze-tags:
    name: Analyze tags
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      timestamp-diff: ${{ steps.diff.outputs.timestamp-diff }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0 # fetch complete history to find the last git tag

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0

      - name: Get seconds from previous tag to now
        id: diff
        shell: bash
        env:
          TIMESTAMP_TAG: ${{ steps.previoustag.outputs.timestamp }}
        run: |
          echo "$(($(printf '%(%s)T') - TIMESTAMP_TAG))"
          echo "timestamp-diff=$(($(printf '%(%s)T') - TIMESTAMP_TAG))" >> "$GITHUB_OUTPUT"

      - name: Debug
        env:
          TIMESTAMP_DIFF: ${{ steps.diff.outputs.timestamp-diff }}
        run: |
          echo "$TIMESTAMP_DIFF"
          echo "-"
          echo "inputs.IS_DEBOUNCED: ${{ inputs.IS_DEBOUNCED }}"
          echo "inputs.IS_DEBOUNCED == '': ${{ inputs.IS_DEBOUNCED == '' }}"
          echo "inputs.IS_DEBOUNCED == null: ${{ inputs.IS_DEBOUNCED == null }}"
          echo "inputs.IS_DEBOUNCED > '': ${{ inputs.IS_DEBOUNCED > '' }}"
          echo "-"
          echo "inputs.IS_DEBOUNCED == false: ${{ inputs.IS_DEBOUNCED == false }}"
          echo "inputs.IS_DEBOUNCED == 'false': ${{ inputs.IS_DEBOUNCED == 'false' }}"
          echo "inputs.IS_DEBOUNCED == true: ${{ inputs.IS_DEBOUNCED == true }}"
          echo "inputs.IS_DEBOUNCED == 'true': ${{ inputs.IS_DEBOUNCED == 'true' }}"
          echo "-"
          echo "steps.diff.outputs.timestamp-diff > 604800: ${{ steps.diff.outputs.timestamp-diff > 604800 }}"
          echo "contains(inputs.IS_DEBOUNCED, 'false') || steps.diff.outputs.timestamp-diff > 604800: ${{ inputs.IS_DEBOUNCED == false || steps.diff.outputs.timestamp-diff > 604800 }}"

  schedule-release:
    name: Schedule release
    runs-on: ubuntu-latest
    needs: analyze-tags
    if: ${{ contains(inputs.IS_DEBOUNCED, 'false') || needs.analyze-tags.outputs.timestamp-diff > 604800 }} # 604800 equal one week.
    steps:
      - name: Checkout git repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # personal access token required for `stefanzweifel/git-auto-commit-action` to trigger workflows on the new commit (https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs)

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: 'fix: schedule release'
          commit_options: '--allow-empty'
          skip_dirty_check: true
